// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoP3ayV2ThVfAd4FJc57OcgbV3uXVmwFQ',
    appId: '1:610510773006:web:92344c5e8ad7e25cd1555f',
    messagingSenderId: '610510773006',
    projectId: 'reservi-e6b17',
    authDomain: 'reservi-e6b17.firebaseapp.com',
    storageBucket: 'reservi-e6b17.firebasestorage.app',
    measurementId: 'G-ZNE04RGGS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk98b8_kj0rV9CY0lsbEdOU4MCdhX3yX8',
    appId: '1:610510773006:android:f777d52731970db1d1555f',
    messagingSenderId: '610510773006',
    projectId: 'reservi-e6b17',
    storageBucket: 'reservi-e6b17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFMAp7A6PWn07aL5yYxKNOmE8rB7Emblg',
    appId: '1:610510773006:ios:9880a7ed2b7a357ed1555f',
    messagingSenderId: '610510773006',
    projectId: 'reservi-e6b17',
    storageBucket: 'reservi-e6b17.firebasestorage.app',
    iosBundleId: 'com.example.reservi1Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFMAp7A6PWn07aL5yYxKNOmE8rB7Emblg',
    appId: '1:610510773006:ios:9880a7ed2b7a357ed1555f',
    messagingSenderId: '610510773006',
    projectId: 'reservi-e6b17',
    storageBucket: 'reservi-e6b17.firebasestorage.app',
    iosBundleId: 'com.example.reservi1Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoP3ayV2ThVfAd4FJc57OcgbV3uXVmwFQ',
    appId: '1:610510773006:web:f81a20edf686a504d1555f',
    messagingSenderId: '610510773006',
    projectId: 'reservi-e6b17',
    authDomain: 'reservi-e6b17.firebaseapp.com',
    storageBucket: 'reservi-e6b17.firebasestorage.app',
    measurementId: 'G-KEP80H9ZZN',
  );
}